management:
  trace:
    enabled: true
    include: AUTHORIZATION_HEADER, COOKIE_HEADERS, PRINCIPAL, REMOTE_ADDRESS, REQUEST_HEADERS, RESPONSE_HEADERS, SESSION_ID, TIME_TAKEN
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web.filter.CommonsRequestLogging: DEBUG
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: TRACE
    reactor.netty.http.client: TRACE

server:
  port: 8443
  forward-headers-strategy: framework
  servlet:
    context-path: /ms-chat-service

spring:
  application:
    name: ms-chat-service
  flyway:
    enabled: true
    baseline-on-migrate : true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-coh7s5f79t8c73fuij7g-a.oregon-postgres.render.com/ms_chat_service
    username: twitter_fnvb_user
    password: bWuOk2kJRpU0EtjUAPRoMhx3UU2ZF7uh
    driverClassName: org.postgresql.Driver

service:
  downstream-url:
    ms-user-service: https://ms-user-service.onrender.com
    ms-tweet-service: https://ms-tweet-service.onrender.com
    ms-websocket-service: https://ms-websocket-service.onrender.com

eureka:
  instance:
    hostname: ms-chat-service.onrender.com  # Public domain name
    nonSecurePort: 443  # Standard HTTP port
    securePortEnabled: true  # Enable if you're using HTTPS
    preferIpAddress: false  # Use the hostname instead of the IP address
    statusPageUrlPath: /actuator/info  # Default status page path
    healthCheckUrlPath: /actuator/health  # Default health check path
  client:
    serviceUrl:
      defaultZone: https://ms-eureka-server-syh2.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true